### ISSUE TITLE
How to use the package?

### ISSUE THREAD

**Issue by Bilonik** [woven/sitemap#2]
Whats the url for the sitemap?

**Comment by jimmyff** [comment]
Hey Bilonik, it's up to you to write the sitemap to a file and make it available somewhere. I tend to send it up to FirebaseStorage and serve it from there.

Something like so:

```dart

Future uploadSitemap(Sitemap sitemap, Storage storage) async {

    var bytes = new Utf8Encoder().convert(sitemap.generate());
    return await storage.ref("sitemap.xml").put(bytes, metadata);
}
```
