### ISSUE TITLE
Any idea about how to use the generated sitemap into the Google Search Console ?

### ISSUE THREAD

**Issue by ben55j** [woven/sitemap#4]
Hello, 

Thank you for this package. I have succeeded to generate my sitemap, but I can figure out about how to make it available for Google. The Google Search Console ask to provide an URL using my website in Flutter like 
https://www.my_flutter_website.com/#/sitemap.xml

In Flutter, it seems not possible to display an XML page.

Any idea about how I should proceed ?

Thank you for your help, 
Benjamin

.

**Comment by jimmyff** [comment]
Hey Ben, this package just generates the sitemap, you'll still need to host it somewhere. As part of my build script I upload my sitemap files to firebase storage / google cloud storage. You will then have a URL to provide Webmaster tools. If you want you can even map your own domain/subdomain to the storage bucket.

I'll close this issue as it's out of scope of this package.

Thanks & good luck
